# Generated by Django 5.2.8 on 2025-11-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_event_color_event_created_at_event_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("Personal", "Personal"),
                    ("Work", "Work"),
                    ("Birthday", "Birthday"),
                ],
                default="Personal",
                max_length=10,
            ),
        ),
    ]
